language: python
python:
  - "3.6"

env:
  global:
    # for $TENDENCI_TRANSIFEX_PASSWORD
    secure: "H3pfvt1czYywa1Fp+quLeWqHOTqZVXDeyoCAFCthi4FO7YYvj8FpaRefUJ8iBIpN/NKImJkGGAh10KWkWXwhwWf2IZQmjTpYRZ0EltkhLyHDIQugoKCnt6VSfPUcrBwZBbA5mBI1JWtSWuN6MnrwMbM9XPpYf4o85OpZZnBdCN8="

# command to install dependencies
install:
  - pip install "Django>=1.11,<2.0"

# TODO: command to run tests
# for now, run command to push source and translation files to Transifex
script: ./transifex.sh

branches:
  only:
    - master
